/***
	=============== Coded by Christian Lewis-Monto. ===============
																	***/
#pragma once

namespace jci {

enum
{
	Keycode_Unknown = 0,
	Keycode_Return = '\r',
	Keycode_Escape = '\x1B',
	Keycode_Backspace = '\b',
	Keycode_Tab = '\t',
	Keycode_Space = ' ',
	Keycode_Exclaim = '!',
	Keycode_DoubleQuote = '"',
	Keycode_Hash = '#',
	Keycode_Percent = '%',
	Keycode_Dollar = '$',
	Keycode_Amersand = '&',
	Keycode_Quote = '\'',
	Keycode_LeftParen = '(',
	Keycode_RightParen = ')',
	Keycode_Asterisk = '*',
	Keycode_Plus = '+',
	Keycode_Comma = ',',
	Keycode_Minus = '-',
	Keycode_Period = '.',
	Keycode_Slash = '/',
	Keycode_0 = '0',
	Keycode_1 = '1',
	Keycode_2 = '2',
	Keycode_3 = '3',
	Keycode_4 = '4',
	Keycode_5 = '5',
	Keycode_6 = '6',
	Keycode_7 = '7',
	Keycode_8 = '8',
	Keycode_9 = '9',
	Keycode_Colon = ':',
	Keycode_Semicolon = ';',
	Keycode_Less = '<',
	Keycode_Equals = '=',
	Keycode_Greater = '>',
	Keycode_Question = '?',
	Keycode_At = '@',
	Keycode_LelftBracket = '[',
	Keycode_Backslash = '\\',
	Keycode_RightBracket = ']',
	Keycode_Caret = '^',
	Keycode_Underscore = '_',
	Keycode_Backquote = '`',
	Keycode_a = 'a',
	Keycode_b = 'b',
	Keycode_c = 'c',
	Keycode_d = 'd',
	Keycode_e = 'e',
	Keycode_f = 'f',
	Keycode_g = 'g',
	Keycode_h = 'h',
	Keycode_i = 'i',
	Keycode_j = 'j',
	Keycode_k = 'k',
	Keycode_l = 'l',
	Keycode_m = 'm',
	Keycode_n = 'n',
	Keycode_o = 'o',
	Keycode_p = 'p',
	Keycode_q = 'q',
	Keycode_r = 'r',
	Keycode_s = 's',
	Keycode_t = 't',
	Keycode_u = 'u',
	Keycode_v = 'v',
	Keycode_w = 'w',
	Keycode_x = 'x',
	Keycode_y = 'y',
	Keycode_z = 'z',
	Button_Left = 1,
	Button_Middle = 2,
	Button_Right = 3,
	Button_X1 = 4,
	Button_X2 = 5
};

} // Namespace jci.